calabozoUPP/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import include,url
from posts.views import home_render
from django.contrib.auth.views import login,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include("posts.urls", namespace='list_post')),
    url(r'^post/', include("posts.urls", namespace='detalle')),
    url(r'^post/', include("posts.urls", namespace='crear_Post')),
    url(r'^home/',include("posts.urls", namespace='home')),
    url(r'^home/',include("posts.urls", namespace='about')),
    url(r'^cuentas/', include("cuentas.urls", namespace='registro')),
    url(r'^cuentas/login/', login, {'template_name':'login_form.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^home/',include("posts.urls", namespace='categorias')),
    url(r'^home/',include("posts.urls", namespace='contacto')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuentas/urls.py
from django.conf.urls import url
from cuentas.views import RegistroUsuario

urlpatterns = [
    url(r'^registrar', RegistroUsuario.as_view(), name="registro"),
]

posts/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import login_required

from  . import views

from .views import (
    detalle_post,
)

urlpatterns = [
    url(r'^$',views.home_render, name='home'),
    url(r'^(?P<id>\d+)/$',detalle_post,name='detalle'),
    url(r'^about',views.about_render, name='about'),
    url(r'^contacto',views.contacto_view, name='contacto'),
    url(r'^list',views.post_list, name='list_post'),
    url(r'^crear',views.crear_post ,name='crear_post'),
    url(r'^categorias',views.categoria_view, name='categ'),
    url(r'^fisico',views.cat_fisico, name='fisico'),
    url(r'^online',views.cat_online, name='online'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='update'),
]

posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify


# Create your models here.

class Post(models.Model):
    titulo = models.CharField(max_length=100)
    categoria = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    imagen = models.ImageField(upload_to="imagenes", blank=True, null=True)
    descripcion = models.TextField()
    fecha = models.DateField(auto_now=False,auto_now_add=True)


    def __str__(self):
        return self.titulo


    class Meta:
        ordering = ["-fecha"]




class Categoria(models.Model):
    titulo = models.CharField(max_length=100,unique=True)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.titulo)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug





def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "titulo",
            "imagen",
            "descripcion",
            "categoria",
        ]

posts/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse,HttpResponseRedirect, Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from posts.models import Post
from posts.forms import PostForm
from django.utils import timezone
from django.db.models import Q

# Create your views here.

def crear_post(request):

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        intance = form.save(commit=False)
        intance.save()
        messages.success(request, "El Post se creo bien mi pequeño padawan")
        post = Post.objects.all()
        contexto = {'posts':post}
        return render(request,"post_list.html",context=contexto)
    contexto = {
        "form": form,
    }
    return render(request, "post_form.html", contexto)

def detalle_post(request, id):
    instancia = get_object_or_404(Post, id=id)
    contexto = {
        "titulo":instancia.titulo,
        "obj":instancia,
    }
    return render(request, "form_detalle.html",context=contexto)

def home_render(request):
    return render(request, "bienvenida.html")

def about_render(request):
    return render(request, "about.html")

def contacto_view(request):
    return render(request,"contacto.html")


def post_list(request):
    #hoy = timezone.now().date()
    queryset_list = Post.objects.all().order_by("-fecha")
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(titulo__icontains=query) |
            Q(descripcion__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 5)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    #post = Post.objects.all()#.order_by("-fecha")
    contexto = {
        "object_list": queryset,
        "page_request_var": page_request_var,
    }

    return render(request,"post_list.html", context=contexto)

    #return HttpResponse("<h1>lista post</h1>")

def categoria_view(request):
    return render(request,"categorias.html")

def cat_fisico(request):
    filtro_post = Post.objects.filter(categoria="fisico")

    #queryset_list = Post.objects.all().order_by("-fecha")

    paginator = Paginator(filtro_post, 5)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    contexto = {
        "object_list": queryset,
        "page_request_var": page_request_var,
    }

    return render(request,"post_list.html",context=contexto)

def cat_online(request):
    filtro_post = Post.objects.filter(categoria="online")

    #queryset_list = Post.objects.all().order_by("-fecha")

    paginator = Paginator(filtro_post, 5)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    contexto = {
        "object_list": queryset,
        "page_request_var": page_request_var,
    }

    return render(request,"post_list.html",context=contexto)

def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)

templates/about.html
{% extends "base.html" %}

{% block content%}


	<!-- +++++ Welcome Section +++++ -->
	<div id="ww">
	    <div class="container">
            {% load static %}
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 centered">
					<img src='{% static "static_img/elsenor.jpg" %}' alt="Stanley" height="300px" width="300px" class="imgCg">
					<h1>Calabozo UPP </h1>
					<p>Comunidad donde puedes compartir tus conocimientos y experiencias en juegos ya sea de cartas como Yu-Gi-Oh!, mesa como Catan o maquinas como KOF.</p>
				</div><!-- /col-lg-8 -->
			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /ww -->




{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>index</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "css/bootstrap.css"%}' rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href='{% static "css/main.css"%}' rel="stylesheet" />
    <link href='{% static "css/mCss.css"%}' rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src='{% static "js/hover.zoom.js" %}'/>
    <script src='{% static "js/hover.zoom.conf.js" %}'></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  {% block heder%}

    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home:home' %}">Calabozo UPP</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'registro:registro' %}">Registrate</a></li>
            <li><a href="{% url 'about:about' %}">Acerca De</a></li>
              <li><a href="{% url 'home:categ' %}">Categorias</a></li>
            <li><a href="{% url 'list_post:list_post' %}">Blog</a></li>
            <li><a href="{% url 'home:contacto'%}">Contacto</a></li>
              <li><a href="{% url 'crear_Post:crear_post'%}">Crear Post</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

  {% endblock %}

  {%block content%}
  {% endblock %}



  {% block footer %}
	<!-- +++++ Footer Section +++++ -->

	<div id="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<h4>Oficinas</h4>
					<p>
						Calle 12 de octubre de 1492, n° 207 Col. Centro<br/>
						Tel: 7713133233, <br/>
						Pachuca de soto, Hidalgo CP.42000.
					</p>
				</div><!-- /col-lg-4 -->

				<div class="col-lg-4">
					<h4>Redes Sociales</h4>
					<p>
						<a href="https://m.youtube.com/channel/UCeEepEN6ANNDWCLuwHU_vEQ">Youtube</a><br/>
						<a href="#">Facebook</a>
					</p>
				</div><!-- /col-lg-4 -->

				<div class="col-lg-4">
				    <h4>Acerca De Nosotros</h4>
					<p>Comunidad donde podrás encontrar lo mas relevante del mundo de los juegos de cartas como Yugioh, Weiss Schwarz y Pokemon, así como juegos de mesa como Catan y maquinas Arcade.</p>
				</div><!-- /col-lg-4 -->

			</div>

		</div>
	</div>

    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src='{% static "js/bootstrap.mim.js" %}'></script>
  </body>
</html>

templates/bienvenida.html
{% extends "base.html" %}


{%block contenido%}
<!-- +++++ pagina bienvenida +++++ -->
	<div id="ww">
	    <div class="container">

			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 centered">
					{% load static %}
					<img src='{% static "static_img/elTeam.jpg" %}' alt="elTeam" height="300px" width="300px" id="imgTeam">
					<h1>Saludos, Somos Guardianes del Calabozo UPP</h1>
					<p>¡Ven y diviértete! Espacio dedicado a ser un centro de reunion donde puedes disfrutar de un espacio para discutir sobre juegos como; TCG’s (Yo-Gi-Oh, Weiss Schwarz, Pokemon) Juegos de mesa (Catan, King of Tokio y mas) Videojuegos (maquinas Arcade).</p>
					<p>Porfavor, registrate <a href="{% url 'registro:registro' %}"> aquí</a> para enterarte de todo lo que pasa en nuestra Comunidad.</p>

				</div><!-- /col-lg-8 -->
			</div><!-- /row -->

	    </div> <!-- /container -->
	</div><!-- /ww -->
{% endblock %}

templates/categorias.html
{% extends "base.html" %}



{% block content %}

<div class="container pt">
    <div class="row mt centered">
        {% load static %}
      <div class="col-lg-4">
        <a class="zoom green imgCg" href="{% url 'home:online' %}"><img class="img-responsive" src='{% static "static_img/WoWFisico.jpg" %}' alt="" width="400px" height="300px" /></a>
        <p>Juegos de Cartas</p>
      </div>
      <div class="col-lg-4">
        <a class="zoom green imgCg" href="{% url 'home:fisico' %}"><img class="img-responsive" src='{% static "static_img/mesa.jpg" %}' alt="" width="400px" height="300px"/></a>
        <p>Juegos de Mesa</p>
      </div>
    </div><!-- /row -->
  </div><!-- /container -->

{% endblock %}

templates/contacto.html
{% extends "base.html" %}

{% block content %}

<div class="container pt">
		<div class="row mt">
			<div class="col-lg-6 col-lg-offset-3 centered">
				<h3>CONTACTANOS</h3>
				<hr>
				<p>Ingresa tus datos Elfo(a) y nosotros te contactamos </p>
			</div>
		</div>
		<div class="row mt">
			<div class="col-lg-8 col-lg-offset-2">
				<form role="form">
				  <div class="form-group">
				    <input type="name" class="form-control" id="NameInputEmail1" placeholder="Tu nombre va aqui">
				    <br>
				  </div>
				  <div class="form-group">
				    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Tu email va aqui">
				    <br>
				  </div>
				  <div class="form-group">
				    <input type="email" class="form-control" id="subjectEmail1" placeholder="Tema">
				    <br>
				  </div>
				  <textarea class="form-control" rows="6" placeholder="Pon tu mensaje aqui"></textarea>
				    <br>
				  <button type="submit" class="btn btn-success">ENVIAR</button>
				</form>
			</div>
		</div><!-- /row -->
	</div><!-- /container -->


{% endblock %}

templates/form_detalle.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<!-- +++++ Post +++++ -->
	<div id="white">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src='{% static "static_img/user.png" %}' width="50px" height="50px"> <ba>Nombre de Usuario</ba></p>
					<p><bd>{{obj.fecha}}</bd></p>
					<h4>{{ obj.titulo }}</h4>
					{%if obj.imagen %}
					<p><img class="img-responsive" src="{{ obj.imagen.url }}" alt=""></p>
					{% endif %}
					<p>{{obj.descripcion}} </p>
					<br>
					<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
					<p><bt>TAGS: <a href="#">esto es un tag</a> - <a href="#">Otro Tag</a></bt></p>
					<hr>
					<p><a href="#">#Comentarios</a></p>
					<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /white -->


{% endblock %}

templates/form_registro.html
{% extends "base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<div class="row mt">
			<div class="col-lg-6 col-lg-offset-3 centered">
				<h3>REGISTRO</h3>
				<hr>
				<p>Ingresa tus datos y enterate de lo mas nuevo de la comunidad</p>
			</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellidos</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>

</form>
{% endblock %}

templates/login_form.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}
{% block content %}


<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>    
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>

{% endblock %}

templates/post_form.html
{% extends "base.html" %}

{% block content %}

<div id="white">
    <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <h1>Crear Post Nuevo</h1>
            <form method='POST' action='' enctype='multipart/form-data'>
                {% csrf_token %}

                {{ form.as_p }}
                <input  type='submit' class='btn btn-success btn-lg' value='Crear Producto' />
</form>
</div>
        </div>
</div>

{% endblock %}

templates/post_list.html
{% extends "base.html" %}


<!-- +++++ Second Post +++++ -->
{% block content %}
	<div id="white">
	    <div class="container">
			<br>
			<br>


            {% load static %}


			<form method='GET' action=''>
					<input type='text' name='q' placeholder='Buscar Post' value='{{ request.GET.q }}'/>
					<input class="btn btn-primary" type='submit' value='Buscar' />
            </form>

			<br>
			<br>
            {% for post in object_list %}
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="thumbnail">
					<p><img src='{% static "static_img/user.png" %}' width="50px" height="50px"> <ba>Otro Nombre de Usuario</ba></p>
					<p><bd>{{ post.fecha}}</bd></p>
					<h4>{{ post.titulo }}</h4>
					{% if post.imagen %}
					<p><img class="img-responsive" src="{{ post.imagen.url }}" alt=""></p>
					{% endif %}
					<p> {{ post.descripcion|linebreaks|truncatechars:80 }} </p>
					<p><a href='/post/{{post.id}}'>Saber mas...</a></p>
					</div>
				</div>

			</div><!-- /row -->

            {% endfor %}

			<div class="pagination">
				<span class="step-links">
					{% if object_list.has_previous %}
					<a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Anterior</a>
					{% endif %}
					<span class="current">
						Pagina {{ object_list.number }} de {{ object_list.paginator.num_pages }}.
					</span>
					{% if object_list.has_next %}
					<a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Siguiente</a>
					{% endif %}
				</span>
			</div>

	    </div> <!-- /container -->

	</div><!-- /white -->

 {% endblock %}